$(document).ready(function(){
    $("#menu2").click(function(){
        $("#panel1").slideToggle("slow");
    });
});
$(document).ready(function(){
    $("#git").click(function(){
        $("#gitPanel").slideToggle("slow");
    });
});