$(document).ready(function(){
    $("#menu2").click(function(){
        $("#panel1").slideToggle("slow");
    });
});
$(document).ready(function(){
    $("#menu3").click(function(){
        $("#panel2").slideToggle("slow");
    });
});